# Generated by Django 5.2.5 on 2025-08-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_nome_autor_autor_rename_nome_editora_editora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='s_nome',
            new_name='s_autor',
        ),
    ]
